// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/Button/AppButton.vue')['default']
    AppDoing: typeof import('./src/components/AppDoing.vue')['default']
    AppDone: typeof import('./src/components/AppDone.vue')['default']
    AppFooter: typeof import('./src/components/Footer/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/Header/AppHeader.vue')['default']
    AppInput: typeof import('./src/components/Inputs/AppInput.vue')['default']
    AppInputText: typeof import('./src/components/Inputs/AppInputText.vue')['default']
    AppLink: typeof import('./src/components/Link/AppLink.vue')['default']
    AppList: typeof import('./src/components/List/AppList.vue')['default']
    AppListItem: typeof import('./src/components/List/AppListItem.vue')['default']
    AppListItemButton: typeof import('./src/components/List/AppListItemButton.vue')['default']
    AppListItemSelector: typeof import('./src/components/List/AppListItemSelector.vue')['default']
    AppListItemText: typeof import('./src/components/List/AppListItemText.vue')['default']
    AppListSelector: typeof import('./src/components/List/AppListSelector.vue')['default']
    AppListWrapper: typeof import('./src/components/AppListWrapper.vue')['default']
    AppSelect: typeof import('./src/components/Select/AppSelect.vue')['default']
    AppSelectOption: typeof import('./src/components/Select/AppSelectOption.vue')['default']
    AppTodo: typeof import('./src/components/AppTodo.vue')['default']
    AppTodoInput: typeof import('./src/components/AppTodoInput.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ListItem: typeof import('./src/components/List/ListItem.vue')['default']
    ListWrapper: typeof import('./src/components/ListWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
